### ISSUE TITLE
Travis CIの導入

### ISSUE THREAD

**Issue by 1995hnagamin** [omni-compiler/ClangXcodeML#11]
自動テストのためTravis CIを導入したい。
​
## Repository ownerにしてほしいこと
1. [Travis CI](https://travis-ci.org/)に登録する(トップページのsign upから行う)
2. "Active GitHub repositories"からClangXcodeMLを有効化する
   ​

詳しい手順については[このページ](http://portaltan.hatenablog.com/entry/2015/07/30/104236)に分かりやすくまとまっています。

**Comment by mnakao** [comment]
たぶん、私の方でTravisCIを設定するよりも、1995hnagamin様の方で設定された方が自由度が高くて良いと思いましたので、1995hnagamin様（とkoyama41様）に、このリポジトリのadmin権限を付与しました。

**Comment by 1995hnagamin** [comment]
導入しました。
https://travis-ci.org/omni-compiler/ClangXcodeML
